<?php



/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends AppEntityRepository
{
    /**
     * @param array $criteria
     * @param array|null $orderBy
     * @param null $limit
     * @param null $offset
     * @return array|Account[]
     */
    public function findByCriteria(array $criteria, ?array $orderBy = null, $limit = null, $offset = null): array
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    public function findOneByCriteria(array $criteria, ?array $orderBy = null): Account|null
    {
        return parent::findOneBy($criteria, $orderBy);
    }

    function findOneById(int|string $id): Account|null
    {
        return parent::find($id);
    }

    function getEntityClassName(): string
    {
        return 'Account';
    }

    static function instance(): AccountRepository
    {
        return new self();
    }
}

