<?php



/**
 * AdministratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministratorRepository extends AppEntityRepository
{
    /**
     * @param array $criteria
     * @param array|null $orderBy
     * @param null $limit
     * @param null $offset
     * @return array|Administrator[]
     */
    public function findByCriteria(array $criteria, ?array $orderBy = null, $limit = null, $offset = null): array
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    public function findOneByCriteria(array $criteria, ?array $orderBy = null): Administrator|null
    {
        return parent::findOneBy($criteria, $orderBy);
    }

    function findOneById(int|string $id): Administrator|null
    {
        return parent::find($id);
    }

    function getEntityClassName(): string
    {
        return 'Administrator';
    }

    /**
     * @return AdministratorRepository
     */
    static function instance(): AdministratorRepository
    {
        return new self();
    }

    public function findOneByUserProfileId(int $userProfileId): ?Administrator
    {
        return $this->findOneByCriteria(['userProfile' => $userProfileId]);
    }
}
