<?php


/**
 * AgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentRepository extends AppEntityRepository
{
    public static function instance(): self
    {
        return new self();
    }

    /**
     * @param array $criteria
     * @param array|null $orderBy
     * @param null $limit
     * @param null $offset
     * @return array|UserProfile[]
     */
    public function findByCriteria(array $criteria, ?array $orderBy = null, $limit = null, $offset = null): array
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    public function findOneByCriteria(array $criteria, ?array $orderBy = null): Agent|null
    {
        return parent::findOneBy($criteria, $orderBy);
    }

    public function findOneById(int|string $id): Agent|null
    {
        return parent::find($id);
    }

    public function getEntityClassName(): string
    {
        return 'Agent';
    }

    public function findOneByUserProfileId(int | string $userProfileId): ?Agent
    {
        return $this->findOneByCriteria(['userProfile' => $userProfileId]);
    }
}

