<?php


/**
 * BranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchRepository extends AppEntityRepository
{
    function findOneByCriteria(array $criteria, ?array $orderBy = null): Branch|null
    {
        return parent::findOneBy($criteria, $orderBy);
    }

    function findOneById(int|string $id): Branch|null
    {
        return parent::find($id);
    }

    /**
     * @param array $criteria
     * @param array|null $orderBy
     * @param int|null $limit
     * @param int|null $offset
     * @return Branch[]
     */
    function findByCriteria(array $criteria, ?array $orderBy = null, ?int $limit = null, ?int $offset = null) : array
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    function getEntityClassName(): string
    {
        return 'Branch';
    }

    static function instance(): BranchRepository
    {
        return new self();
    }
}
