<?php

use Doctrine\ORM\EntityManager;


/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends AppEntityRepository
{
    /**
     * @param array $criteria
     * @param array|null $orderBy
     * @param null $limit
     * @param null $offset
     * @return Client[]
     */
    public function findByCriteria(array $criteria, ?array $orderBy = null, $limit = null, $offset = null): array
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    public function findOneByCriteria(array $criteria, ?array $orderBy = null): Client|null
    {
        return parent::findOneBy($criteria, $orderBy);
    }

    function findOneById(int|string $id): Client|null
    {
        return parent::find($id);
    }

    function getEntityClassName(): string
    {
        return 'Client';
    }

    /**
     * @return ClientRepository
     */
    static function instance(): ClientRepository
    {
        return new self();
    }

    public function findOneByUserProfileId(int $userProfileId) : ?Client
    {
        return $this->findOneByCriteria(['userProfile' => $userProfileId]);
    }
}

