<?php



/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends AppEntityRepository
{
    /**
     * @param array $criteria
     * @param array|null $orderBy
     * @param null $limit
     * @param null $offset
     * @return array|Transaction[]
     */
    public function findByCriteria(array $criteria, ?array $orderBy = null, $limit = null, $offset = null): array
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    public function findOneByCriteria(array $criteria, ?array $orderBy = null): Transaction|null
    {
        return parent::findOneBy($criteria, $orderBy);
    }

    function findOneById(int|string $id): Transaction|null
    {
        return parent::find($id);
    }

    function getEntityClassName(): string
    {
        return 'Transaction';
    }

    static function instance(): TransactionRepository
    {
       return new self();
    }
}
