<?php


/**
 * UserProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileRepository extends AppEntityRepository
{

    /**
     * @param array $criteria
     * @param array|null $orderBy
     * @param null $limit
     * @param null $offset
     * @return array|UserProfile[]
     */
    public function findByCriteria(array $criteria, ?array $orderBy = null, $limit = null, $offset = null): array
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    public function findOneByCriteria(array $criteria, ?array $orderBy = null): UserProfile|null
    {
        return parent::findOneBy($criteria, $orderBy);
    }

    public function findOneById(int|string $id): UserProfile|null
    {
        return parent::find($id);
    }

    public function getEntityClassName(): string
    {
        return 'UserProfile';
    }

    static function instance(): UserProfileRepository
    {
        return new self();
    }
}

